name: mobi
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2023.08.22=h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - decorator=5.1.1=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gh=2.52.0=he0e2781_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.5.0=py38h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.0=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.8.0=h0371630_2
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=7.0=h7b6447c_5
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - albumentations==0.4.3
    - antlr4-python3-runtime==4.8
    - anyio==4.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.15.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==5.3.3
    - certifi==2024.6.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.2
    - defusedxml==0.7.1
    - descartes==1.1.0
    - diffusers==0.29.2
    - einops==0.3.0
    - exceptiongroup==1.2.2
    - executing==2.0.1
    - fastjsonschema==2.20.0
    - filelock==3.15.4
    - fire==0.6.0
    - fonttools==4.53.0
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - ftfy==6.2.0
    - future==1.0.0
    - google-auth==2.30.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.64.1
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - idna==3.7
    - imageio==2.34.2
    - imgaug==0.2.6
    - imhist==0.0.4
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - imwatermark==0.0.2
    - ipykernel==6.29.5
    - ipython==8.12.3
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - lightning-utilities==0.11.2
    - llvmlite==0.31.0
    - loguru==0.7.2
    - lpips==0.1.4
    - markdown==3.6
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - msgpack==1.0.8
    - msgpack-numpy==0.4.8
    - multidict==6.0.5
    - multimethod==1.10
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.1
    - ninja==1.11.1.1
    - notebook-shim==0.2.4
    - numba==0.48.0
    - numpy==1.22.0
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - opencv-python==4.10.0.84
    - overrides==7.7.0
    - packaging==24.1
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parameterized==0.9.0
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.2.2
    - point-cloud-utils==0.30.4
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.47
    - protobuf==5.27.2
    - psutil==6.0.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycocotools==2.0.7
    - pycparser==2.22
    - pydeprecate==0.3.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytorch-lightning==1.4.5
    - pytz==2024.1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==26.0.3
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.19.0
    - rsa==4.9
    - safetensors==0.4.3
    - scikit-image==0.20.0
    - scikit-learn==1.3.2
    - scipy==1.9.1
    - send2trash==1.8.3
    - setuptools==59.5.0
    - shapely==1.8.5.post1
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - tensorpack==0.11
    - termcolor==2.4.0
    - terminado==0.18.1
    - terminaltables==3.1.10
    - test-tube==0.7.5
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tinycss2==1.3.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - torchmetrics==0.6.0
    - torchpack==0.3.1
    - tornado==6.4.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transformers==4.19.2
    - types-python-dateutil==2.9.0.20240316
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.2
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.0.3
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.19.2